name: find_gadget
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.4
  shrink_sidemenu: ^2.0.0+2-null-safety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/font/
  fonts:
    - family: Raleway-B
      fonts:
        - asset: assets/font/Raleway-Bold.ttf
    - family: Raleway-Ex-B
      fonts:
        - asset: assets/font/Raleway-ExtraBold.ttf
    - family: Raleway-S-B
      fonts:
        - asset: assets/font/Raleway-SemiBold.ttf
    - family: Raleway-R
      fonts:
        - asset: assets/font/Raleway-Regular.ttf